from .detectors import CaptchaDetector, WaitingPageDetector
from .drughub_detectors import DrughubCaptchaDetector, DrughubWaitingPageDetector
from .cocorico_detectors import CocoricoCaptchaDetector, CocoricoWaitingPageDetector